# Window constants
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
DEFAULT_FPS = 60
WINDOW_TITLE = "PONG"

# Boundaries
UPPER_BOUND = 5
LOWER_BOUND = SCREEN_HEIGHT - 5

# Paddle constants
PADDLE_WIDTH = 8
PADDLE_HEIGHT = 70
PADDLE_CENTERPOINT = PADDLE_HEIGHT / 2

# Object coordinates and movement
PLAYER_XPOS = 5
PLAYER_YPOS = (SCREEN_HEIGHT / 2) - PADDLE_CENTERPOINT
CPU_XPOS = SCREEN_WIDTH - PADDLE_WIDTH - 5
CPU_YPOS = (SCREEN_HEIGHT / 2) - PADDLE_CENTERPOINT
BALL_VELOCITY = 6
BALL_RADIUS = 5
BALL_INITIALX = int(SCREEN_WIDTH / 2)
BALL_INITIALY = int(SCREEN_HEIGHT / 2)
