# Window constants
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 500
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
DEFAULT_FPS = 60
WINDOW_TITLE = "PONG"


# Paddle constants
PADDLE_WIDTH = 30
PADDLE_HEIGHT = 100
PADDLE_CENTERPOINT = PADDLE_HEIGHT/2


# Object coordinates and movement
PLAYER_XPOS = 20
PLAYER_YPOS = (SCREEN_HEIGHT/2) - PADDLE_CENTERPOINT
CPU_XPOS = SCREEN_WIDTH - 60
CPU_YPOS = (SCREEN_HEIGHT/2) - PADDLE_CENTERPOINT
BALL_VELOCITY = 4
BALL_RADIUS = 8
